# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k2ykNvZx2DjUL6zFz6-aUMnC6wT2ypfE
"""

name = str(input("Enter your name here "))
iteration = len(name)
for i in range(0, iteration ):
  for j in range(0, iteration):
    if(j == i ):
      print(name[j], sep="",end='*')
    else:
      print("*",sep=" ",end="")
  print()